name: taqa_dl
channels:
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - aom=3.6.0
  - blas=1.0
  - brotlicffi=1.0.9.2
  - bzip2=1.0.8
  - ca-certificates=2025.7.15
  - cairo=1.16.0
  - certifi=2025.8.3
  - cffi=1.17.1
  - charset-normalizer=3.3.2
  - cpuonly=2.0
  - dav1d=1.2.1
  - expat=2.7.1
  - ffmpeg=4.3
  - filelock=3.17.0
  - fontconfig=2.14.1
  - freetype=2.13.3
  - fribidi=1.0.10
  - giflib=5.2.2
  - gmp=6.3.0
  - gmpy2=2.2.1
  - gnutls=3.6.15
  - graphite2=1.3.14
  - harfbuzz=10.2.0
  - icu=73.1
  - idna=3.7
  - intel-openmp=2023.1.0
  - jinja2=3.1.6
  - jpeg=9e
  - lame=3.100
  - lcms2=2.16
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libavif=1.1.1
  - libdeflate=1.22
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libglib=2.84.2
  - libgomp=11.2.0
  - libiconv=1.16
  - libidn2=2.3.4
  - libjpeg-turbo=2.0.0
  - libpng=1.6.39
  - libstdcxx-ng=11.2.0
  - libtasn1=4.19.0
  - libtiff=4.7.0
  - libunistring=0.9.10
  - libuuid=1.41.5
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libxcb=1.17.0
  - libxml2=2.13.8
  - llvm-openmp=14.0.6
  - lz4-c=1.9.4
  - markupsafe=3.0.2
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - ncurses=6.5
  - nettle=3.7.3
  - networkx=3.4.2
  - openh264=2.1.1
  - openjpeg=2.5.2
  - openssl=3.0.17
  - pcre2=10.42
  - pillow=11.3.0
  - pip=25.1
  - pixman=0.40.0
  - pthread-stubs=0.3
  - pycparser=2.21
  - pysocks=1.7.1
  - python=3.11.13
  - pytorch=2.5.1
  - pytorch-mutex=1.0
  - pyyaml=6.0.2
  - readline=8.3
  - requests=2.32.4
  - setuptools=78.1.1
  - sqlite=3.50.2
  - tk=8.6.14
  - torchaudio=2.5.1
  - torchvision=0.20.1
  - wheel=0.45.1
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxrender=0.9.12
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - yaml=0.2.5
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
      - adagio==0.2.6
      - aiofiles==24.1.0
      - alembic==1.16.4
      - annotated-types==0.7.0
      - ansi2html==1.9.2
      - antlr4-python3-runtime==4.11.1
      - anyio==4.10.0
      - aplr==10.9.0
      - appdirs==1.4.4
      - asttokens==3.0.0
      - attrs==25.3.0
      - beautifulsoup4==4.13.4
      - blinker==1.9.0
      - boto3==1.40.6
      - botocore==1.40.6
      - brotli==1.1.0
      - cachetools==5.5.2
      - catboost==1.2.8
      - category-encoders==2.7.0
      - choreographer==1.0.9
      - click==8.2.1
      - cloudpickle==3.1.1
      - colorlog==6.9.0
      - colour==0.1.5
      - comm==0.2.3
      - contourpy==1.3.3
      - cryptography==45.0.6
      - cycler==0.12.1
      - cython==3.1.2
      - daal==2025.7.0
      - dacite==1.9.2
      - dash==2.18.2
      - dash-auth==2.3.0
      - dash-bootstrap-components==1.7.1
      - dash-core-components==2.0.0
      - dash-cytoscape==1.0.2
      - dash-html-components==2.0.0
      - dash-table==5.0.0
      - dash-testing-stub==0.0.2
      - dask==2025.7.0
      - databricks-sdk==0.62.0
      - debugpy==1.8.16
      - decorator==5.2.1
      - deprecation==2.1.0
      - dill==0.4.0
      - distributed==2025.7.0
      - distro==1.9.0
      - docker==7.1.0
      - dtreeviz==2.2.2
      - dynaconf==3.2.11
      - evidently==0.4.40
      - executing==2.2.0
      - explainerdashboard==0.5.1
      - fairlearn==0.7.0
      - faker==37.5.3
      - fastapi==0.116.1
      - fastjsonschema==2.21.1
      - ffmpy==0.6.1
      - flask==2.3.3
      - flask-simplelogin==0.2.0
      - flask-wtf==1.2.2
      - fonttools==4.59.0
      - fs==2.4.16
      - fsspec==2025.7.0
      - fugue==0.8.7
      - fugue-sql-antlr==0.2.2
      - future==1.0.0
      - gevent==25.5.1
      - gitdb==4.0.12
      - gitpython==3.1.45
      - google-auth==2.40.3
      - gradio==5.42.0
      - gradio-client==1.11.1
      - graphene==3.4.3
      - graphql-core==3.2.6
      - graphql-relay==3.2.0
      - greenlet==3.2.4
      - groovy==0.1.2
      - gunicorn==23.0.0
      - h11==0.16.0
      - hf-xet==1.1.7
      - htmlmin==0.1.12
      - httpcore==1.0.9
      - httptools==0.6.4
      - httpx==0.28.1
      - huggingface-hub==0.34.4
      - hyperopt==0.2.7
      - imagehash==4.3.1
      - imbalanced-learn==0.13.0
      - importlib-metadata==8.7.0
      - iniconfig==2.1.0
      - interpret==0.7.2
      - interpret-core==0.7.2
      - ipykernel==6.30.1
      - ipython==9.4.0
      - ipython-pygments-lexers==1.1.1
      - ipywidgets==8.1.7
      - iterative-telemetry==0.0.10
      - itsdangerous==2.2.0
      - jedi==0.19.2
      - jmespath==1.0.1
      - joblib==1.3.2
      - jsonschema==4.25.0
      - jsonschema-specifications==2025.4.1
      - jupyter-client==8.6.3
      - jupyter-core==5.8.1
      - jupyter-dash==0.4.2
      - jupyterlab-widgets==3.0.15
      - kaleido==1.0.0
      - kiwisolver==1.4.8
      - kmodes==0.12.2
      - lightgbm==4.6.0
      - litestar==2.17.0
      - litestar-htmx==0.5.0
      - llvmlite==0.44.0
      - locket==1.0.0
      - logistro==1.1.0
      - lxml==6.0.0
      - m2cgen==0.10.0
      - mako==1.3.10
      - markdown-it-py==3.0.0
      - matplotlib==3.7.5
      - matplotlib-inline==0.1.7
      - mdurl==0.1.2
      - mlflow==3.2.0
      - mlflow-skinny==3.2.0
      - mlflow-tracing==3.2.0
      - mlxtend==0.23.4
      - moto==4.2.14
      - msgpack==1.1.1
      - msgspec==0.19.0
      - multidict==6.6.3
      - multimethod==1.12
      - multipart==1.3.0
      - multiprocess==0.70.18
      - mypy-extensions==1.1.0
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - nltk==3.9.1
      - numba==0.61.0
      - numpy==1.26.4
      - nvidia-nccl-cu12==2.27.7
      - opentelemetry-api==1.36.0
      - opentelemetry-sdk==1.36.0
      - opentelemetry-semantic-conventions==0.57b0
      - optuna==4.4.0
      - optuna-integration==4.4.0
      - orjson==3.11.1
      - outcome==1.3.0.post0
      - oyaml==1.0
      - packaging==25.0
      - pandas==2.1.4
      - parso==0.8.4
      - partd==1.4.2
      - patsy==1.0.1
      - percy==2.0.2
      - pexpect==4.9.0
      - phik==0.12.5
      - platformdirs==4.3.8
      - plotly==5.24.1
      - plotly-resampler==0.10.0
      - pluggy==1.6.0
      - pmdarima==2.0.4
      - polyfactory==2.22.1
      - prompt-toolkit==3.0.51
      - protobuf==6.31.1
      - psutil==7.0.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - puremagic==1.30
      - py4j==0.10.9.9
      - pyaml==25.7.0
      - pyarrow==21.0.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pycaret==3.3.2
      - pydantic==2.11.7
      - pydantic-core==2.33.2
      - pydub==0.25.1
      - pygments==2.19.2
      - pynndescent==0.5.13
      - pyod==2.0.5
      - pyopenssl==25.1.0
      - pyparsing==3.2.3
      - pytest==7.4.4
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.1.1
      - python-multipart==0.0.20
      - pytz==2025.2
      - pywavelets==1.9.0
      - pyzmq==27.0.1
      - qpd==0.4.4
      - referencing==0.36.2
      - regex==2025.7.34
      - responses==0.25.8
      - retrying==1.4.2
      - rich==14.1.0
      - rich-click==1.8.9
      - rpds-py==0.27.0
      - rsa==4.9.1
      - ruff==0.12.8
      - s3transfer==0.13.1
      - safehttpx==0.1.6
      - salib==1.5.1
      - schemdraw==0.15
      - scikit-base==0.7.8
      - scikit-learn==1.4.2
      - scikit-learn-intelex==2025.7.0
      - scikit-optimize==0.10.2
      - scikit-plot==0.3.7
      - scipy==1.11.4
      - seaborn==0.13.2
      - selenium==4.2.0
      - semantic-version==2.10.0
      - shap==0.44.1
      - shellingham==1.5.4
      - simplejson==3.20.1
      - six==1.17.0
      - sklearn-compat==0.1.3
      - sktime==0.26.0
      - slicer==0.0.7
      - smmap==5.0.2
      - sniffio==1.3.1
      - sortedcontainers==2.4.0
      - soupsieve==2.7
      - sqlalchemy==2.0.42
      - sqlglot==27.6.0
      - sqlparse==0.5.3
      - stack-data==0.6.3
      - starlette==0.47.2
      - statsforecast==1.5.0
      - statsmodels==0.14.5
      - sympy==1.13.1
      - tbats==1.1.3
      - tbb==2022.2.0
      - tblib==3.1.0
      - tcmlib==1.4.0
      - tenacity==9.1.2
      - threadpoolctl==3.6.0
      - tomlkit==0.13.3
      - toolz==1.0.0
      - tornado==6.5.2
      - tqdm==4.67.1
      - traitlets==5.14.3
      - triad==0.9.8
      - trio==0.30.0
      - trio-websocket==0.12.2
      - tsdownsample==0.1.4.1
      - typeguard==4.4.4
      - typer==0.16.0
      - typing-extensions==4.14.1
      - typing-inspect==0.9.0
      - typing-inspection==0.4.1
      - tzdata==2025.2
      - ujson==5.10.0
      - umap-learn==0.5.7
      - urllib3==1.26.20
      - urllib3-secure-extra==0.1.0
      - uuid6==2025.0.1
      - uvicorn==0.35.0
      - uvloop==0.21.0
      - visions==0.8.1
      - waitress==3.0.2
      - watchdog==6.0.0
      - watchfiles==1.1.0
      - wcwidth==0.2.13
      - websockets==15.0.1
      - werkzeug==2.3.8
      - widgetsnbextension==4.0.14
      - wordcloud==1.9.4
      - wsproto==1.2.0
      - wtforms==3.2.1
      - wurlitzer==3.1.1
      - xgboost==3.0.3
      - xmltodict==0.14.2
      - xxhash==3.5.0
      - ydata-profiling==4.16.1
      - yellowbrick==1.5
      - zict==3.0.0
      - zipp==3.23.0
      - zope-event==5.1.1
      - zope-interface==7.2
